- name: pull images on all hosts
  docker_image:
    name: "{{ repository_deploy_image }}"
    source: pull
  loop: "{{ groups['docker_swarm_nodes'] }}"
  delegate_to: "{{ item }}"
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
